services:
  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: speechBox_postgres
      POSTGRES_USER: speechBox_postgres
      POSTGRES_PASSWORD: speechBox_postgres
    ports:
      - "6543:5432"
  redis:
    image: redis
    ports:
      - "6378:6379"
