volumes:
  db_data:
  db_data_test:
  redis_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db_pg_16
      - redis

  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: speechBox_postgres
      POSTGRES_USER: speechBox_postgres
      POSTGRES_PASSWORD: speechBox_postgres
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  app2:
    build:
      context: ../../gameService/SpeechBoxServerGameManagement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"